### ISSUE TITLE
Authentication code error message

### ISSUE THREAD

**Issue by Focinfi** [tinfoil/devise-two-factor#51]
If user got a authentication code error, the error message is still 'Invalid email or password.', how to specify the message to some sentence like 'Authentication code is wrong'?

**Comment by HugoPouliquen** [comment]
+1

**Comment by ZempTime** [comment]
in `config/locales/devise.en.yml` you can set the majority of the message Devise uses.

to do authentication on login specifically, look for the `invalid` entry, and change it something like this:

```
en:
  devise:
    failure:
      invalid: "Invalid %{authentication_keys}, one-time-use code, or password."
```

**Comment by mattcg** [comment]
@ZempTime that is helpful, but I don't think it works around the original issue, which is that it should be possible for a specific message to be shown when the authentication is invalid but the username and password are valid.

**Comment by mattcg** [comment]
It's possible to display a specific message when only the authentication code is incorrect with a few changes to your model and the Devise language configuration file.

```ruby
#app/models/user.rb
#...

  def unauthenticated_message
    if @failed_otp
      :invalid_otp
    else
      super
    end
  end

  def validate_and_consume_otp!(code, options = {})
    @failed_otp = !super(code, options)
    return !@failed_otp
  end

  private
  
  @failed_otp = false

#...
```

```yaml
#config/locales/devise.en.yml

en:
  devise:
    failure:
      invalid_otp: "Invalid authentication code."
```
